import { FaGithub } from "react-icons/fa";

export const myProjects = [
  {
    projectTitle: "Alkarasa Library",
    category: ["wordpress"],
    imgPath: "/images/1.PNG",
    projectDescription: [
      "This innovative web application is designed to facilitate buying and selling products. You can pay using bank cards and mobile wallets!",
    ],
    url: "https://daralkarasa-eg.com/",
    github:"https://daralkarasa-eg.com/",
  },
  {
    projectTitle: " Online Store for Furniture & Home Appliances",
    category: ["wordpress"],
    imgPath: "/images/11.PNG",
    projectDescription: [
      "A full-featured e-commerce website for a client specializing in furniture and home appliances. The platform allows customers to seamlessly browse a wide range of products",
    ],
    url: "https://gawhara.store/",
    github:"https://gawhara.store/",
  },
  {
    projectTitle: "Amazon clone using react ",
    category: ["react"],
    imgPath: "/images/2.PNG",
    projectDescription: [
      " Developed a frontend user interface mimicking Amazon using React.js and modern libraries to enhance user experience, using Redux Toolkit For centralized state management, Formik For form management and data handling",
    ],
    url: "https://amazon-redux.vercel.app/",
    github:"https://github.com/Mohamed-fayez22/Amazon-clone",
  },
  { 
    projectTitle: "Dynamic Shopping cart", 
    category: ["react"], 
    imgPath: "/images/3.PNG",
    projectDescription:["Developed a dynamic shopping cart website using React-Context API and Firebase, allowing users to browse products, view details, and manage their cart with real-time updates,Integrated currency formatting for a user-friendly display of prices.",
],
url: "https://shopping-cart-firebase.vercel.app/store",
github:"https://github.com/Mohamed-fayez22/shopping-cart-firebase",
  },
  {
    projectTitle: "DynamicPortfolio",
    category: ["react"],
    imgPath: "/images/4.PNG",
    projectDescription: ["Designed and developed a personal portfolio website to showcase my projects, skills, and experience. The website includes a section for displaying fake projects fetched dynamically to demonstrate my ability to handle API integration and data rendering.",
    ],
    url: "https://movie-app-with-react-two.vercel.app/",
    
  },
  { projectTitle: "React+Tailwand project",
     category: ["tailwand","react"],
      imgPath: "/images/5.PNG" ,
      projectDescription:["Developed a dynamic web application using React and Tailwind CSS to demonstrate my proficiency in modern frontend development and utility-first CSS frameworks,Created reusable and interactive React components to enhance user experience,Leveraged Tailwind’s utility classes to design a clean, modern, and visually appealing interface",
],
url: "https://tailwandpro-react-vite.vercel.app/",

},
  { projectTitle: "React+Tailwand project",
     category: ["tailwand","react"],
      imgPath: "/images/6.PNG" ,
      projectDescription:["Developed a dynamic web application using React and Tailwind CSS to demonstrate my proficiency in modern frontend development and utility-first CSS frameworks,Created reusable and interactive React components to enhance user experience,Leveraged Tailwind’s utility classes to design a clean, modern, and visually appealing interface",
],
url: "https://coffe-tailwand-project.vercel.app/",
},
  { projectTitle: "Facebook clone",
     category: ["html","css"],
      imgPath: "/images/7.PNG" ,
      projectDescription:[" Designed and developed a static clone of the Facebook user interface using HTML and CSS to demonstrate my skills in frontend development and responsive design.",
],
url: "https://facebook-clone-three-murex.vercel.app/",
},
  { projectTitle: "Static Portfolio ",
     category: ["html","css"],
      imgPath: "/images/8.PNG" ,
      projectDescription:["Designed and developed a static portfolio website using HTML and CSS to showcase my skills, projects, and experience in a clean and professional manner.",
],
url: "https://portfolio-html-css-ashy.vercel.app/",
},
  { projectTitle: "Turbo Website",
     category: ["html","css"],
      imgPath: "/images/9.PNG" ,
      projectDescription:[" Designed and developed a static website for a fictional application called Turbo using HTML and CSS. The website showcases the app’s features, benefits, and call-to-action sections in a visually appealing and user-friendly manner.",
],
url: "https://turbo-website-beta.vercel.app/#",
},
  { projectTitle: "Dashboard",
     category: ["html","css"],
      imgPath: "/images/10.PNG",
      projectDescription:[" website showcases the app’s features, benefits, and call-to-action sections in a visually appealing and user-friendly manner.",
],
url: "https://dashboard-roan-alpha.vercel.app/#index.html",
},

];
